version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: corpExp2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: OrderDatabase
      MYSQL_USER: corpExp2
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
